<template>
    <div class="p-4">
        <input v-model="searchQuery" placeholder="輸入物料號或名稱" class="border p-2 rounded w-full mb-4" />
        <table class="w-full border-collapse border border-gray-300">
            <thead>
                <tr class="bg-gray-200">
                    <th class="border p-2">物料號</th>
                    <th class="border p-2">名稱</th>
                    <th class="border p-2">單位</th>
                    <th class="border p-2">一箱數量</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="item in filteredData" :key="item.id" class="border">
                    <td class="border p-2">{{ item.id }}</td>
                    <td class="border p-2">{{ item.name }}</td>
                    <td class="border p-2">{{ item.unit }}</td>
                    <td class="border p-2">{{ item.quantity }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<script setup>
import { ref, computed } from 'vue';

const searchQuery = ref('');
const data = ref([
    {
        id: '11007000-11',
        name: '斯帕德8毫克菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '110901-11',
        name: '長壽黃硬盒菸(鋁箔)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '1109N0-11',
        name: '長壽黃硬盒菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '110R40-11',
        name: '馬爾斯長支5毫克菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '110S30-11',
        name: '馬爾斯長支2毫克菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '110UQ0-11',
        name: '尊爵G5',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '110Z20-11',
        name: '維斯塔7毫克(圓角包)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '111201-11',
        name: '新樂園10號香菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '1113N0-11',
        name: '寶島天葉10號香菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '1118F0-11',
        name: '長壽白軟包菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '111A20-11',
        name: '維斯塔5毫克(圓角包)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '111LM0-11',
        name: '馬爾斯綠星球菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '111LM0-38',
        name: '馬爾斯綠星球菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '111ZN6-11',
        name: '王牌21 T9',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '112AN6-11',
        name: '王牌21 T6',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '112BN6-11',
        name: '王牌21 T3',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '112CN6-11',
        name: '王牌21 T1',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '112K03-11',
        name: '馬爾斯長支23 M8',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '112N00-11',
        name: 'LaRose玫瑰冰心',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '112U00-11',
        name: '金絲頓8毫克菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '1135H0-11',
        name: '馬爾斯M9',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '113640-11',
        name: '尊爵白金G10',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '1138Q0-11',
        name: '尊爵G7',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '113Q01-11',
        name: '馬爾斯紫繽星球菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '1145Q0-11',
        name: '尊爵G3',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '1149N0-11',
        name: '長壽白軟包7毫克菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '114A00-11',
        name: '馬爾斯水星球菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '115030-11',
        name: '尊爵白金G6',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '1154Q0-11',
        name: '尊爵G1',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '119201-11',
        name: '尊爵白金GI國際包',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '119201-38',
        name: '尊爵白金GI國際包',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12000000-11',
        name: '百樂門湛藍20支香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12001000-11',
        name: '百樂門20支香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '121501-11',
        name: '尊爵白金纖細GS',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '1251N0-11',
        name: '寶島天葉7號香菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '125201-11',
        name: '新樂園7號香菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '125301-11',
        name: '新樂園5號香菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '127130-11',
        name: '尊爵白金G2',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '128901-11',
        name: '新樂園1號香菸',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12AM10-11',
        name: '萬寶路金20支香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12CB00-11',
        name: '萬寶路冰球MEGA 20支薄荷香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12CF10-11',
        name: '樂邁晶球FORWARD紅20支香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12CG10-11',
        name: '樂邁晶球FORWARD藍20支香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12CH10-11',
        name: '樂邁晶球FORWARD白20支香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12CR00-11',
        name: '萬寶路黑冰20支薄荷香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12D330-11',
        name: '鋒樂邁紅20支香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12D430-11',
        name: '鋒樂邁藍20支香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12D510-11',
        name: '鋒樂邁綠20支薄荷香菸(圓角包)(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12D600-11',
        name: '萬寶路20支香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12D700-11',
        name: '維珍妮冰珠20支薄荷香菸(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12DJ10-11',
        name: '萬寶路紅工藝 CRAFTED20 支香菸(硬盒)(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '12DK10-11',
        name: '萬寶路金工藝 CRAFTED20 支香菸(硬盒)(代工-PM)',
        unit: 'BAG',
        quantity: '500  ',
    },
    {
        id: '21008000-14',
        name: '0.5公升瓶裝台啤特釀黑麥啤酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21008001-14',
        name: '0.5公升*4罐裝台啤特釀黑麥啤酒',
        unit: 'SET',
        quantity: '6  ',
    },
    {
        id: '21010000-14',
        name: '0.33公升罐裝台啤特釀研究室‧白色迷霧',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21010001-14',
        name: '0.33公升*6罐台啤特釀研究室‧白色迷霧',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21010002-14',
        name: '0.6公升瓶裝台啤特釀研究室‧白色迷霧',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '210208-14',
        name: '1.2公升玉泉陳年紹興酒',
        unit: 'JA',
        quantity: '6  ',
    },
    {
        id: '21021001-14',
        name: '0.5公升*4罐裝台啤特釀．橙喚NEIPA',
        unit: 'SET',
        quantity: '6  ',
    },
    {
        id: '21025005-34',
        name: '0.33公升罐裝台啤微醺系列芭樂蓮霧啤酒(外銷)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21025006-14',
        name: '0.33公升*6罐裝台啤微醺系列芭樂蓮霧啤酒',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21025006-34',
        name: '0.33公升*6罐裝台啤微醺系列芭樂蓮霧啤酒(外銷)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21029000-14',
        name: '0.5公升*4罐裝金牌118天鮮台灣啤酒',
        unit: 'SET',
        quantity: '6  ',
    },
    {
        id: '21031001-14',
        name: '0.33公升*6罐裝金牌ONE台灣啤酒',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21031001-34',
        name: '0.33公升*6入罐裝金牌ONE台灣啤酒(外銷)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21031003-14',
        name: '0.6公升瓶裝12入金牌ONE台灣啤酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21031004-14',
        name: '0.5公升*4罐裝金牌ONE台灣啤酒',
        unit: 'SET',
        quantity: '6  ',
    },
    {
        id: '21031013-14',
        name: '0.5公升*4罐裝金牌ONE台灣啤酒(期間限定H)',
        unit: 'SET',
        quantity: '6  ',
    },
    {
        id: '21031017-14',
        name: '0.33公升*6罐裝金牌ONE台灣啤酒 (期間限定J)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '210400-14',
        name: '0.6公升台灣啤酒',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '210405-14',
        name: '0.5公升罐裝台灣啤酒',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '210473-14',
        name: '0.33公升*6罐裝台灣啤酒(紙盒包裝)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '2104B5-14',
        name: '0.5公升*4罐裝台灣啤酒(紙盒包裝)',
        unit: 'SET',
        quantity: '6  ',
    },
    {
        id: '2104C3-14',
        name: '0.33公升罐裝台灣啤酒',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21052000-14',
        name: '40公升桶裝台灣生啤酒(水果系列-草莓)',
        unit: 'DR',
        quantity: '0  ',
    },
    {
        id: '21053000-14',
        name: '0.33公升*6罐裝台啤微醺系列百香芒果啤酒',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21056000-14',
        name: '0.33公升罐裝金牌PLUS台灣啤酒',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21057000-14',
        name: '0.33公升瓶裝祝山極光啤酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '211009-14',
        name: '1.8公升玉泉花雕酒(瓷)',
        unit: 'JA',
        quantity: '4  ',
    },
    {
        id: '211017-14',
        name: '27公升八秩晉一花雕酒(16.5%)(八秩晉一公司)',
        unit: 'JA',
        quantity: '0  ',
    },
    {
        id: '211070-14',
        name: '0.6公升玉泉花雕酒(15%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '211960-14',
        name: '0.6公升玉泉精釀陳年紹興酒(15.5%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21407001-14',
        name: '0.5公升鮮啤特急･蜂潮(花蓮)',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '21407002-14',
        name: '0.33公升深蜜之水(澐游國際有限公司)',
        unit: 'BT',
        quantity: '40  ',
    },
    {
        id: '21407003-14',
        name: '0.33公升深蜜之水(國立故宮博物院聯名)',
        unit: 'BT',
        quantity: '40  ',
    },
    {
        id: '21408000-14',
        name: '0.5公升鮮啤特急･洄瀾山瓜IPA(花蓮)',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '214605-14',
        name: '0.5公升罐裝金牌台灣啤酒',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '214605-34',
        name: '0.5公升罐裝金牌台灣啤酒(外銷大陸)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '214673-14',
        name: '0.33公升*6罐裝金牌台灣啤酒(紙盒包裝)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '214680-14',
        name: '0.6公升瓶裝金牌台灣啤酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '2146B5-14',
        name: '0.5公升*4罐裝金牌台灣啤酒(紙盒包裝)',
        unit: 'SET',
        quantity: '6  ',
    },
    {
        id: '2146C3-14',
        name: '0.33公升罐裝金牌台灣啤酒',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '2146C3-34',
        name: '0.33公升金牌台灣啤酒(罐裝)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '2146D5-14',
        name: '0.5公升*4罐裝金牌台灣啤酒(期間限定D)',
        unit: 'SET',
        quantity: '6  ',
    },
    {
        id: '2146D6-14',
        name: '0.33公升瓶裝金牌台灣啤酒(回收瓶)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '214801-14',
        name: '3公升十年窖藏精釀陳紹甕酒',
        unit: 'JA',
        quantity: '4  ',
    },
    {
        id: '215606-14',
        name: '1.35公升玉泉窖藏金雞老紅酒',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '215610-14',
        name: '1.1公升玉泉窖藏金雞老紅酒(樂居宜蘭)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2156C8-14',
        name: '0.6公升*2玉泉窖藏金雞老紅酒禮盒(普款)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2156E1-14',
        name: '0.1公升玉泉窖藏金雞老紅酒',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '2156G1-14',
        name: '0.1公升玉泉窖藏金雞老紅酒(石港春帆)',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '2156H1-14',
        name: '0.1公升玉泉窖藏金雞老紅酒(縣酒)',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '2156K1-14',
        name: '0.1公升玉泉窖藏金雞老紅酒(湯圍溫泉)',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '217000-14',
        name: '0.6公升玉泉純米清酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '217208-14',
        name: '1.8公升玉泉台灣之美-純米吟釀禮盒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '217510-14',
        name: '0.6公升玉泉金雞陳年紅露酒(15.5%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '2197A0-14',
        name: '0.6公升瓶裝台灣生啤酒(18天)',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '21A4M1-14',
        name: '10公升桶裝金牌台灣啤酒',
        unit: 'DR',
        quantity: '0  ',
    },
    {
        id: '21A4M2-14',
        name: '20公升桶裝金牌台灣啤酒',
        unit: 'DR',
        quantity: '0  ',
    },
    {
        id: '21A4M3-14',
        name: '30公升桶裝金牌台灣啤酒',
        unit: 'DR',
        quantity: '0  ',
    },
    {
        id: '21CB03-14',
        name: '0.33公升罐裝台啤果微醺(荔枝)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CB03-34',
        name: '0.33公升罐裝台灣啤酒果微醺(荔枝)(外銷大陸)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CB73-34',
        name: '0.33公升*6罐裝台灣啤酒果微醺(荔枝)(紙盒包裝)(外銷)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21CC03-14',
        name: '0.33公升罐裝台啤果微醺(白葡萄)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CC03-34',
        name: '0.33公升罐裝台灣啤酒果微醺(白葡萄)(外銷大陸)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CCC3-34',
        name: '0.33公升罐裝台灣啤酒果微醺(白葡萄)(一般外銷)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CH03-14',
        name: '0.33公升罐裝台啤水果系列(芒果)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CH03-34',
        name: '0.33公升罐裝台灣啤酒水果系列(芒果)(外銷)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CH73-34',
        name: '0.33公升*6罐裝台灣水果啤酒(芒果)(紙盒包裝)(外銷)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21CJ03-14',
        name: '0.33公升罐裝台啤水果系列(鳳梨)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CJ03-34',
        name: '0.33公升罐裝台灣啤酒水果系列(鳳梨)(外銷)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CJ73-34',
        name: '0.33公升*6罐裝台灣水果啤酒(鳳梨)(紙盒包裝)(外銷)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21CM03-14',
        name: '0.33公升罐裝台啤水果系列(葡萄)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CM03-34',
        name: '0.33公升罐裝台啤水果系列(葡萄)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CS03-14',
        name: '0.33公升罐裝台灣啤酒蜂蜜啤酒',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CS03-34',
        name: '0.33公升罐裝台灣啤酒蜂蜜啤酒',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CS73-14',
        name: '0.33公升*6罐裝台灣啤酒蜂蜜啤酒(紙盒包裝)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21CW03-14',
        name: '0.33公升罐裝台灣啤酒果微醺(葡萄柚)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21CW03-34',
        name: '0.33公升罐裝台灣啤酒果微醺(葡萄柚)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21D619-14',
        name: '0.33公升*6罐裝台啤特釀研究室 金色年華',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21D701-14',
        name: '0.33公升*6罐裝爽啤(ecopack包裝)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21D705-14',
        name: '0.5公升罐裝爽啤',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21D710-14',
        name: '0.6公升瓶裝爽啤(1年期)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21D719-14',
        name: '0.33公升*6罐裝爽啤(1年期)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '21D723-14',
        name: '0.33公升罐裝爽啤(1年期)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21DC03-14',
        name: '0.33公升罐裝金牌台灣啤酒-荔枝',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '21GS00-14',
        name: '0.5公升*4罐裝台啤特釀．向陽IGA',
        unit: 'SET',
        quantity: '6  ',
    },
    {
        id: '21J010-14',
        name: '0.6公升玉泉黃酒(酒精度13%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21J102-14',
        name: '0.3公升十五年窖藏公賣局古越廬山埔里坊御製紹興酒(聚規玻璃瓶裝)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21J802-14',
        name: '0.75公升玉泉台灣埔里坊窖藏20年精釀陳紹禮盒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '21J809-14',
        name: '0.9公升玉泉20年精釀陳紹－不倒甕',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '21JM00-14',
        name: '0.6公升玉泉特級紅露酒(14%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21JMA0-14',
        name: '0.6公升玉泉特級紅露酒(14%)訂製',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21JQ10-14',
        name: '0.6公升玉泉陳年紹興酒(14.5%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21JR10-14',
        name: '0.6公升玉泉紹興酒(13%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21JS00-14',
        name: '0.6公升玉泉清酒(13.5%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '21JT06-14',
        name: '2公升玉泉甕藏18年花雕酒',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '21JT11-14',
        name: '0.3公升玉泉陳年花雕酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '21JZ06-14',
        name: '1.35公升玉泉窖藏12年金雞老紅酒(龜山朝日)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '21JZ16-14',
        name: '1.35公升玉泉窖藏12年金雞老紅酒(石港春帆)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '21JZ26-14',
        name: '1.35公升玉泉窖藏12年金雞老紅酒(湯圍溫泉)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '21JZ36-14',
        name: '1.35公升玉泉窖藏12年金雞老紅酒(北關海潮)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '21K105-14',
        name: '0.5公升菊富士生貯藏清酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '22000000-14',
        name: '0.75公升花酵母白葡萄酒．山櫻花',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '220902-14',
        name: '0.75公升玉泉特級玫瑰紅酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '221502-14',
        name: '0.75公升玉泉金香白葡萄酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '221600-14',
        name: '0.6公升玉泉特級紅葡萄酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '221701-14',
        name: '0.75公升玉泉荔枝酒(烘培專用)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '22172A-14',
        name: '0.375公升*2玉泉荔枝酒禮盒',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '222002-14',
        name: '0.75公升玉泉紅麴葡萄酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '222202-14',
        name: '0.75公升玉泉極品紅麴葡萄酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '222209-14',
        name: '0.75公升*2玉泉極品紅麴葡萄酒禮盒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '222412-14',
        name: '0.75公升玉泉洋蔥紅酒(新標)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '223762-14',
        name: '0.75公升玉泉紅麴葡萄酒(金標)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '224100-14',
        name: '0.75公升JADE SPRING 精選紅葡萄酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '224172-14',
        name: '0.75公升玉泉台灣之美紅葡萄酒(幾何圖形版)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23003000-14',
        name: '0.7公升台灣釀酒120週年紀念酒OMAR原桶強度單一麥芽威士忌(55.5)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23005000-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-雪莉桶57.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23005001-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-雪莉桶56.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23005002-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-雪莉桶52.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23005003-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-雪莉桶53.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23005004-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-雪莉桶58.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23005007-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-雪莉桶54.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23006001-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-波本桶55.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23006002-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-波本桶58.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23006006-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-波本桶54.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23006007-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-波本桶57.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23006009-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-波本桶56.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23009000-14',
        name: '0.7公升御舞金黃金八年陳高禮盒(52%)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23010000-14',
        name: '0.7公升御舞金黃金六年陳高禮盒(40%)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23011000-14',
        name: '0.7公升御舞金黃金高粱禮盒(40%)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23013000-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-新橡木桶55.0%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23013002-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-新橡木桶54.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23013003-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-新橡木桶55.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23013004-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-新橡木桶56.0%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23013004-39',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-新橡木桶56.0%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23013006-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小麥-新橡木桶53.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23016001-14',
        name: '0.7公升穀蘊原桶強度單一穀類威士忌(小米-波本桶)(52.5%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23018000-14',
        name: '0.95公升杜藏35年陳高(龍騰雲萃)',
        unit: 'BOX',
        quantity: '1  ',
    },
    {
        id: '23019000-14',
        name: '0.36公升再見南國燒酒(原味)',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '23019002-14',
        name: '0.36公升再見南國燒酒(檸檬風味)',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '23023006-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本57.9)(蛇我其誰-昇恆昌)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023007-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木56.6)(蛇我其誰-昇恆昌)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023008-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌禮盒(波本桶57.2)(采盟NO.10)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023009-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌禮盒(波本桶55.7)(采盟NO.11)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023010-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌禮盒(新橡木55.6)(采盟NO.12)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023011-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌禮盒(新橡木55.6)(采盟NO.13)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023012-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌禮盒(波本桶55.4)(采盟NO.14)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023013-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌禮盒(新橡木58.0)(采盟NO.15)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023014-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌禮盒(波本桶54.8)(昇恆昌栓口瓶)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023015-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌禮盒(新橡木56.3)(昇恆昌栓口瓶)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023016-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌禮盒(波本桶55.5)(昇恆昌栓口瓶)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23023017-39',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌禮盒(新橡木57.9)(昇恆昌栓口瓶)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '230242-14',
        name: '0.75公升玉山台灣原窖高粱酒禮盒（柿柿如意）',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23024A-14',
        name: '0.6公升玉山台灣高粱酒(瓷瓶)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23024B-14',
        name: '0.3公升玉山高粱酒(54%)(統一專售)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '230250-14',
        name: '0.6公升玉山高粱酒三年陳高(可可金)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '230290-14',
        name: '0.6公升玉山3年台灣高粱酒禮盒(平安福佑)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2302A4-14',
        name: '10公升玉山台灣原窖1950',
        unit: 'JA',
        quantity: '0  ',
    },
    {
        id: '2302C2-14',
        name: '0.75公升玉山台灣原窖高粱酒(111年春節紀念酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '2302N7-14',
        name: '0.7公升玉山台灣高粱酒(辛亥革命百年紀念酒)(裸瓶裝)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '231101-14',
        name: '0.3公升玉山茅台酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '231155-14',
        name: '0.5公升玉山茅台酒(瓷)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '2318D0-14',
        name: '0.6公升玉尊威士忌(黑盒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '232300-14',
        name: '0.6公升玉山陳年清香高粱酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '232407-14',
        name: '0.7公升愛蘭白酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '232500-14',
        name: '0.6公升玉山清香高粱酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '232700-14',
        name: '0.6公升玉山大武醇',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '2330A0-14',
        name: '0.6公升玉山台灣六年陳高',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '233302-14',
        name: '0.75公升瓷瓶玉山二鍋頭',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '233319-14',
        name: '2公升瓷瓶玉山二鍋頭(106年版)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '233601-14',
        name: '0.66公升玉山頂級陳高(免稅限定)',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '233602-39',
        name: '0.75公升玉山頂級陳高禮盒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '233603-36',
        name: '0.35公升鴿耀祥洲-頂級陳高',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '233608-14',
        name: '0.66公升玉山頂級陳高',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '233610-14',
        name: '0.66公升+0.08公升玉山頂級陳高禮盒(龍年節慶版)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23366K-14',
        name: '0.66公升+0.08公升玉山頂級陳高禮盒(106年版)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2336A4-39',
        name: '0.66公升*2玉山頂級陳高(促銷包)',
        unit: 'BAG',
        quantity: '6  ',
    },
    {
        id: '2336A8-39',
        name: '0.08公升玉山頂級陳高',
        unit: 'BT',
        quantity: '35  ',
    },
    {
        id: '2336B4-39',
        name: '0.66公升*2玉山頂級陳高禮盒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2336G7-14',
        name: '0.7公升中山先生紀念酒-台灣原窖5年頂級陳高禮盒(仿故宮青瓷)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2336G7-34',
        name: '0.7公升中山先生紀念酒-台灣原窖5年頂級陳高禮盒(仿故宮青瓷)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2336J7-39',
        name: '0.7公升中山先生紀念酒（新版）',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '234205-34',
        name: '0.5公升玉山五糧陳酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '234297-14',
        name: '0.7公升玉山五糧陳酒禮盒（添加奈米金）',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '234700-14',
        name: '0.5公升*2玉山金八年陳高(皇與后)塑膠盒裝',
        unit: 'BOX',
        quantity: '5  ',
    },
    {
        id: '234702-14',
        name: '0.7公升玉山金雙倍奈米黃金高粱酒八年陳高',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '234705-14',
        name: '0.5公升玉山金八年陳高(皇)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '234709-14',
        name: '1.5公升玉山金黃金高粱酒8年陳高禮盒(潛龍爭輝)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '234715-14',
        name: '0.5公升玉山金八年陳高(后)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '234729-14',
        name: '0.5公升*2玉山金八年陳高禮盒(皇與后)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '234739-14',
        name: '1.5公升玉山金黃金高粱酒8年陳高禮盒(飛鳳騰達)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '2347B2-14',
        name: '0.75公升玉山金雙倍奈米金八年陳高禮盒(龍吟)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '235330-14',
        name: '0.6公升公賣局特級紅標純米酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '235391-14',
        name: '0.3公升公賣局特級紅標純米酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23540B-14',
        name: '0.6公升玉山珍藏陳高禮盒(火車藝術瓷瓶)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23540D-39',
        name: '1.0公升玉山八年陳高禮盒(金雞報喜)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23540E-39',
        name: '0.9公升玉山台灣原窖8年陳高禮盒(水渲)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23540N-39',
        name: '1.0公升玉山8年陳高禮盒(小龍開運)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23540P-14',
        name: '1.0公升玉山8年陳高禮盒(芳蘭送瑞)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23540Q-39',
        name: '1.0公升玉山台灣原窖8年陳高禮盒(富貴吉鯉)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23540T-39',
        name: '1.0公升玉山八年陳高禮盒(吉羊迎春)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23540U-39',
        name: '1.0公升玉山八年陳高禮盒(祥猴迎春)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '235412-14',
        name: '0.5公升*2玉山八年陳高禮盒(招財迎福)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '235419-39',
        name: '0.9公升玉山台灣原窖8年陳高禮盒(張克齊—躍馬奔騰)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23541G-39',
        name: '1.3公升玉山台灣原窖8年陳高禮盒(飛煌騰達)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23541H-14',
        name: '1.3公升台灣原窖八年陳高禮盒（馬到成功）',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23541J-14',
        name: '1.3公升玉山台灣原窖八年陳高禮盒(吉羊如意)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '235421-14',
        name: '0.3公升玉山台灣原窖8年陳高(玉山圖品評用酒)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23547B-14',
        name: '27公升玉山台灣原窖八年陳高小龍紀念酒(飛煌騰達)',
        unit: 'JA',
        quantity: '0  ',
    },
    {
        id: '23547C-14',
        name: '27公升玉山八年陳高(小龍開運)',
        unit: 'JA',
        quantity: '0  ',
    },
    {
        id: '2354A9-39',
        name: '0.7公升+0.1公升玉山台灣原窖8年陳高禮盒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2354G5-39',
        name: '0.5公升玉山珍藏陳高(駿馬奔騰)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '2354J7-14',
        name: '0.7公升玉山台灣原窖八年陳高(瓷瓶玉山圖)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '2354J9-39',
        name: '0.5公升×2台灣原窖珍藏陳高-8年（富貴雙星）',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '2354K7-14',
        name: '0.7公升玉山台灣原窖8年陳高(双囍臨門)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2354T5-14',
        name: '0.5公升玉山八年陳高(吉羊迎春)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2354W5-14',
        name: '0.5公升玉山八年陳高禮盒(金雞報喜)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '235501-14',
        name: '2.0公升玉山特曲高粱酒禮盒(兔)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '235502-14',
        name: '1.0公升玉山特曲高粱酒(龍)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '235504-14',
        name: '2.0公升玉山特曲高粱酒(龍)',
        unit: 'BT',
        quantity: '4  ',
    },
    {
        id: '2355L2-14',
        name: '2.0公升玉山特曲高粱酒禮盒(喜迎旺臨)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '2355M1-14',
        name: '1.0公升玉山特曲高粱酒禮盒(喜迎富貴)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2355M2-14',
        name: '2.0公升玉山特曲高粱酒禮盒(喜迎富貴)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '2355N2-14',
        name: '2.0公升玉山特曲高粱酒禮盒(鼠)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '2355P2-14',
        name: '2.0公升玉山特曲高粱酒禮盒(牛)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23600B-39',
        name: '0.7公升玉山高粱酒5年陳高禮盒(飛躍台北)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '236085-14',
        name: '0.5公升玉山台灣紅高粱酒(紅瓷瓶)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '236205-14',
        name: '0.6公升玉山台灣52度特級紅高粱',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '236207-14',
        name: '2公升玉山台灣52度特級紅高粱酒禮盒',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '236264-14',
        name: '1.0公升玉山台灣特級紅高粱酒12年陳高禮盒(絕代風華)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23670A-14',
        name: '5公升玉山台灣峯頂16年陳高禮盒(喜鵲飛臨福韻報)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23670F-39',
        name: '0.3+0.7公升玉山台灣峯頂16年陳高禮盒(富韻呈雙)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '236712-39',
        name: '0.75公升玉山台灣峯頂16年陳高禮盒(金玉滿堂)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '236727-14',
        name: '0.7公升玉山台灣峯頂16年陳高(第二屆玉山秋拍紀念)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '236729-14',
        name: '1.5公升玉山台灣峯頂16年陳高禮盒(翠玉白菜)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '236739-39',
        name: '1.5公升玉山台灣峯頂16年陳高禮盒(富貴風華)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '236743-14',
        name: '1.2公升玉山峯頂珍藏陳高禮盒(富貴桐花)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '236747-14',
        name: '0.7公升玉山台灣峯頂16年陳高(第三屆慈善秋拍紀念酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '236757-14',
        name: '0.7公升玉山台灣峯頂16年陳高(第四屆慈善秋拍紀念酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '236759-39',
        name: '1.5公升玉山台灣峯頂16年陳高禮盒(喜象昇平)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '236763-39',
        name: '1.2公升玉山台灣峯頂16年陳高禮盒(五彩繽紛)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '236769-14',
        name: '1.5公升玉山台灣峯頂16年陳高禮盒(八方集祥)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '236778-14',
        name: '1.5公升玉山台灣峯頂16年陳高禮盒(龍天護佑)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '236778-39',
        name: '1.5公升玉山台灣峯頂16年陳高禮盒(龍天護佑)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '2367A2-39',
        name: '0.7公升玉山台灣峯頂16年陳高禮盒(雙龍獻瑞)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2367A8-14',
        name: '1.5公升玉山峯頂陳高-第12任總統/副總統就職紀念(駿馬奔騰)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '2367B1-39',
        name: '1公升金悅橙祥-玉山16年峯頂珍藏陳高禮盒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2367B3-34',
        name: '1.2公升玉山峯頂珍藏陳高禮盒(春暖花開)(紙盒)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '2367C3-34',
        name: '1.2公升玉山峯頂珍藏陳高禮盒(富貴桐花)(紙盒)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '2367C8-14',
        name: '1.5公升玉山台灣峯頂16年陳高禮盒(駿馬賜福)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '2367F1-39',
        name: '1.0公升玉山16年峯頂陳高禮盒(金榜啼鳴)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2367H1-14',
        name: '1.0公升玉山台灣峯頂16年陳高禮盒(金躍福臨)(第13任總統副總統就職紀念酒)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2367H1-39',
        name: '1.0公升玉山台灣峯頂16年陳高禮盒(金躍福臨)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '2367P1-39',
        name: '1.0公升玉山台灣峯頂16年陳高禮盒(闔家團圓)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '236900-14',
        name: '0.6公升玉山五八金高粱酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '236901-14',
        name: '0.3公升玉山五八金高粱酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '237707-34',
        name: '0.7公升外銷玉山五八金陳高禮盒',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '237707-39',
        name: '0.7公升玉山五八金陳高禮盒',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '237927-14',
        name: '0.7公升玉尊台灣威士忌(新標)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '238001-14',
        name: '0.6公升玉山金黃金高粱酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '238009-14',
        name: '0.6公升*2玉山金黃金高粱酒',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '238528-14',
        name: '1.0公升玉山陳年二鍋頭禮盒(和氣生財)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '238592-14',
        name: '0.7公升玉山陳年二鍋頭禮盒(吉祥如意)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23A112-14',
        name: '0.7公升玉尊經典台灣威士忌(新標)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23A16B-14',
        name: '0.2公升玉尊經典台灣威士忌(新標)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23A400-14',
        name: '1.5公升玉山十二年峯頂珍藏陳高(柿柿如意)_2024年版',
        unit: 'BT',
        quantity: '2  ',
    },
    {
        id: '23A409-14',
        name: '1.5公升玉山峯頂陳高(駿馬奔騰)(12年玉山珍藏陳高)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23A409-39',
        name: '1.5公升玉山峯頂陳高(駿馬奔騰)(12年玉山珍藏陳高)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23A429-39',
        name: '1.5公升玉山12年峯頂珍藏陳高禮盒(柿柿如意)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23A431-14',
        name: '1公升玉山12年峯頂陳高禮盒(明潭映福)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23A441-14',
        name: '1公升玉山12年峯頂陳高禮盒(巍峨獻壽)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23A488-14',
        name: '1公升玉山峯頂陳高-第12任總統/副總統就職紀念(鴿耀祥洲)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23A4B8-14',
        name: '1.0公升12年峯頂陳高禮盒(百世千秋-建國百年紀念酒)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23A807-14',
        name: '0.6公升大麴酒(蔣公87歲壽酒)(60週年慶懷舊紀念酒禮盒)',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '23A808-14',
        name: '0.6公升大麴酒(蔣公88歲壽酒)(60週年慶懷舊紀念酒禮盒)',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '23B100-14',
        name: '0.7公升臺鐵經典車站(紀念酒)(臺南驛)(臺鐵客製化)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23B807-14',
        name: '0.7公升玉台黃金純麥威士忌禮盒(麥亂舞)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23C212-14',
        name: '0.5公升豐原慈濟宮建廟三百年五朝清醮紀念酒(玉山台灣高粱酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23C232-14',
        name: '0.75公升玉山台灣高粱酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23C251-14',
        name: '0.3公升*5玉山台灣高粱酒(五路財神珍藏版)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23C2A0-14',
        name: '0.6公升玉山台灣高粱酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23C2A1-14',
        name: '0.3公升玉山台灣高粱酒(58%)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23C901-14',
        name: '0.7公升玉山陳年臺灣高粱酒(招財進寶)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23C904-14',
        name: '3.0公升玉山陳年臺灣高粱酒(招財進寶)',
        unit: 'BOX',
        quantity: '2  ',
    },
    {
        id: '23C923-14',
        name: '1.0公升陳年台灣高粱酒禮盒(金錢豹)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23C936-39',
        name: '0.2公升*2經國先生百年誕辰紀念酒( 自售)(夫妻篇+小孩篇)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23C9AA-14',
        name: '0.7公升299042/299064-玉山陳年臺灣高粱酒禮盒用(八家將-范將軍)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23C9BB-14',
        name: '0.7公升299042.299064-玉山陳年臺灣高粱酒禮盒用(八家將-謝將軍)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23C9M4-14',
        name: '0.7公升玉山陳年臺灣高粱酒(台灣藝術之美-廖德政)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23C9M4-39',
        name: '0.7公升玉山陳年臺灣高粱酒(台灣藝術之美-廖德政)',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '23C9P4-39',
        name: '0.7公升玉山陳年臺灣高粱酒(台灣藝術之美-李石樵)',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '23C9R4-39',
        name: '0.7公升玉山陳年臺灣高粱酒(台灣藝術之美-楊三郎)',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '23C9T2-14',
        name: '1.0公升玉山陳年台灣高粱酒禮盒(欣欣向榮)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23F100-14',
        name: '0.6公升玉山三年38度高粱酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23F600-14',
        name: '0.7公升玉山窖藏16年愛蘭白酒禮盒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23F70B-14',
        name: '10公升大武古酒',
        unit: 'JA',
        quantity: '0  ',
    },
    {
        id: '23F70C-14',
        name: '15公升大武古酒',
        unit: 'JA',
        quantity: '0  ',
    },
    {
        id: '23F809-39',
        name: '1公升玉山陳年茅台酒',
        unit: 'BT',
        quantity: '9  ',
    },
    {
        id: '23F825-34',
        name: '0.345公升玉山陳年茅台酒',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23G100-14',
        name: '0.6公升玉山三年58度高粱酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23G105-14',
        name: '0.5公升玉山三年台灣高粱酒(黑瓷瓶)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23G10A-34',
        name: '0.12公升外銷玉山三年台灣高粱酒(黑瓷瓶)',
        unit: 'BT',
        quantity: '48  ',
    },
    {
        id: '23H212-14',
        name: '0.75公升玉山台灣特饌高粱酒禮盒(新大吉大利)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23H800-14',
        name: '0.6公升公賣局米酒頭',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23H935-39',
        name: '0.5公升台灣原窖1950十五年陳年高粱酒(喜紅釉)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23J129-39',
        name: '1.0公升玉山台灣原窖12年陳高禮盒(春臨花燦)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23J139-39',
        name: '1.0公升玉山台灣原窖12年陳高禮盒(巍峨獻壽珍藏版)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23J149-39',
        name: '1.0公升玉山台灣原窖12年陳高禮盒(明潭映福珍藏版)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23J175-14',
        name: '0.5公升玉山台灣原窖12年陳高禮盒(葫蘆瓶)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23J175-34',
        name: '0.5公升玉山台灣原窖12年陳高禮盒(葫蘆瓶)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23J1B5-39',
        name: '0.5公升*2玉山台灣原窖12年陳高禮盒（富貴吉祥）',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23K0D5-14',
        name: '5.0公升玉山台灣原窖1950高粱酒(深耕致富)',
        unit: 'JA',
        quantity: '2  ',
    },
    {
        id: '23K0J2-14',
        name: '0.75公升玉山台灣原窖高粱酒(102年端午紀念酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23K0M2-14',
        name: '0.75公升玉山台灣原窖高粱酒(103年端午紀念酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23K0N2-14',
        name: '0.75公升玉山台灣原窖高粱酒(103年秋節紀念酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23K101-14',
        name: '0.3公升玉山泡盛',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23K635-14',
        name: '0.5公升台灣原窖1950五年陳年高粱酒(台灣藝術之美-陳澄波)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23K645-14',
        name: '0.5公升台灣原窖1950五年陳年高粱酒(台灣藝術之美-廖德政)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23K665-14',
        name: '0.5公升台灣原窖1950五年陳年高粱酒(台灣藝術之美-李石樵)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23K685-14',
        name: '0.5公升台灣原窖1950五年陳年高粱酒(台灣藝術之美-楊三郎)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23K705-34',
        name: '0.5公升台灣原窖1950八年陳年高粱酒(大陸)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23K901-14',
        name: '0.3公升玉山台灣參茸酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23L001-14',
        name: '0.3公升玉山台灣鹿茸酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23L702-14',
        name: '0.7公升玉山台灣原窖高粱酒六年陳高',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23L704-14',
        name: '0.5公升玉山台灣原窖六年陳高(龍騰福躍)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23L708-14',
        name: '1.3公升玉山台灣原窖六年陳高禮盒(金梅映福)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23L709-14',
        name: '1.5公升玉山台灣原窖六年陳高禮盒(晶采年年)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23L710-14',
        name: '0.6公升玉山高粱酒六年陳高(黑標)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23L730-14',
        name: '0.6公升玉山高粱酒六年陳高(冰河銀)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23N600-14',
        name: '0.6公升玉山台灣原窖1950高粱酒(52％)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23N601-14',
        name: '0.3公升玉山台灣原窖1950高粱酒（52％）',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23N602-14',
        name: '5公升玉山台灣原窖1950高粱酒(光耀龍門)2024',
        unit: 'JA',
        quantity: '2  ',
    },
    {
        id: '23N608-14',
        name: '0.08公升玉山台灣原窖1950高粱酒（52％）',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23N608-39',
        name: '0.08公升玉山台灣原窖1950高粱酒(52%)',
        unit: 'BT',
        quantity: '48  ',
    },
    {
        id: '23N611-14',
        name: '0.3公升玉山台灣原窖(品評用酒)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23N620-34',
        name: '0.6公升玉山台灣原窖1950高粱酒(52%)(單盒裝)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23N620-39',
        name: '0.6公升玉山台灣原窖1950高粱酒(52%)(單盒裝)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23N640-14',
        name: '0.6公升玉山台灣原窖1950高粱酒禮盒(小飲)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23N675-14',
        name: '5.0公升玉山台灣原窖1950高粱酒(吉羊如意)',
        unit: 'JA',
        quantity: '2  ',
    },
    {
        id: '23N6B5-14',
        name: '5.0公升玉山台灣原窖1950高粱酒(富貴長春)',
        unit: 'JA',
        quantity: '2  ',
    },
    {
        id: '23N6C5-14',
        name: '5.0公升玉山台灣原窖1950高粱酒(子孫滿堂)',
        unit: 'JA',
        quantity: '2  ',
    },
    {
        id: '23N801-14',
        name: '0.5公升玉山台灣高粱酒(事事粽意)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23N8R2-14',
        name: '0.75公升玉山台灣高粱酒禮盒(平安好運)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23NF04-14',
        name: '12公升玉山台灣峯頂24年陳高禮盒(瓜瓞綿延)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23NF17-14',
        name: '0.7公升玉山台灣峯頂24年陳高(非賣品)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23NF27-14',
        name: '0.7公升玉山台灣峯頂24年陳高(第三屆慈善秋拍紀念酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23NF37-14',
        name: '0.7公升玉山台灣峯頂24年陳高(第四屆慈善秋拍紀念酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23NH00-14',
        name: '0.7公升玉尊麥芽威士忌(新版)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23NY09-14',
        name: '0.9公升玉山台灣茶酒(高山烏龍)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P401-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木桶57.8)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P402-14',
        name: '0.7公升圓山總統行館牛年典藏白金波本單桶原酒(波本桶57.8)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P408-14',
        name: '0.7公升圓山總統行館牛年典藏鎏金波本單桶原酒(波本桶57.4)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P429-14',
        name: '0.7公升OMAR圓山總統行館兔年典藏白金波本單桶原酒(波本桶56.5)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P430-14',
        name: '0.7公升OMAR圓山總統行館兔年典藏白金波本單桶原酒(波本桶55.7)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P431-14',
        name: '0.7公升OMAR圓山總統行館兔年典藏鎏金梅子酒桶原酒(梅子酒桶53.4%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P433-39',
        name: '0.7公升OMAR原桶強度麥芽威士忌禮盒(新橡木桶57.9)(昇恆昌專售)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P435-39',
        name: '0.7公升OMAR原桶強度麥芽威士忌禮盒(波本桶56.9)(昇恆昌專售)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P462-39',
        name: '0.7公升原桶強度麥芽威士忌禮盒(新橡木桶57.4%)(采盟專售)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P463-39',
        name: '0.7公升原桶強度麥芽威士忌禮盒(波本桶56.4)(采盟專售)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P465-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(柳丁酒桶)(57%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P47F-14',
        name: '0.7公升OMAR原桶強度泥煤麥芽威士忌(波本桶57.8)(虎之選訂製)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P47G-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(PX雪莉桶53.9)(虎之選訂製)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P483-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(葡萄酒桶)(53%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P488-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶55.9)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P489-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶54.9)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P490-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶53.5)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P491-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶52.4)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P492-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶54.4)(台灣的黃金)(佳賀)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P493-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶54.8)(天下)(玄星)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P495-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶56.0)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P498-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶56.8)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P499-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶55.3)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4A0-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶54.5)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4A1-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶57.3)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4A2-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶54.1)(無雙)(玄星)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4A5-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶54.2)(鋐釀酒坊)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4A8-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本53.8)(水社龍噬月-大爵)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4B1-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木桶58.5)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4B2-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木58.1)(鋐釀酒坊)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4B3-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木56.0)(台灣味)(佳賀)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4B5-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木58.1)(超好喝)(佳賀)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4B8-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木57.1)(年年有魚)(佳賀)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4C2-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木57.1)(虎躍呈祥)(虎躍)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4C8-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌圓山總統行館龍年典藏白金波本桶56.3%',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4C9-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌圓山總統行館龍年典藏鎏金葡萄桶52%',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4CM-14',
        name: '0.7公升原桶強度麥芽威士忌(波本桶50.3)(藏香館公司)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4CN-14',
        name: '0.7公升原桶強度麥芽威士忌(波本桶56.0)(藏香館公司)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4D0-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌圓山總統行館龍年典藏白金波本桶56.8%',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4DP-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木桶56.9)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4DY-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶56.5)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4DZ-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶57.0)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4E0-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶56.2)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4E1-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶57.0)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4E2-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶55.0)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4E5-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶54.3)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4E9-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶56.5)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4EB-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶56.7)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4ED-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木桶57.5)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4EG-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木桶57.2)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4EH-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木桶56.6)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4EJ-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木桶58.0)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4EM-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶54.7)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4EP-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(梅子酒桶)(53%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4EQ-14',
        name: '0.7公升OMAR圓山總統行館虎年典藏鎏金波本單桶原酒(波本桶54.3)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4ER-14',
        name: '0.7公升OMAR圓山總統行館虎年典藏白金波本單桶原酒(波本桶56.8)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4ES-14',
        name: '0.7公升OMAR圓山總統行館虎年典藏白金新橡木單桶原酒(新橡木桶56.0)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4ET-14',
        name: '0.7公升OMAR圓山總統行館虎年典藏鎏金新橡木單桶原酒(新橡木桶58.7)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4EW-14',
        name: '0.7公升原桶強度單一麥芽威士忌(波本桶55.0)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4EX-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木桶58.5)(黑白道2)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4EY-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木桶59.2)(五行－金虎)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4EZ-14',
        name: '0.7公升原桶強度單一泥煤麥芽威士忌(新橡木桶55.3)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4F0-14',
        name: '0.7公升原桶強度麥芽威士忌(新橡木桶58.7)(FRUITY APE)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4F2-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌圓山總統行館龍年典藏白金波本桶54.8%',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4F4-14',
        name: '0.5公升OMAR原桶強度單一麥芽威士忌(雪莉桶55.7)(扶輪社-愛在林梢)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23P4G0-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(柳丁酒桶)(56%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4G1-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(梅子酒桶)(54%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4G5-14',
        name: '0.5公升OMAR原桶強度單一麥芽威士忌(雪莉桶55.7)(扶輪社-老幹新枝)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23P4G6-14',
        name: '0.5公升OMAR原桶強度單一麥芽威士忌(雪莉桶55.7)(扶輪社-花語系列三)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23P4G8-14',
        name: '0.5公升OMAR原桶強度單一麥芽威士忌(雪莉桶55.7)(扶輪社-春之竹林)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23P4G9-14',
        name: '0.5公升OMAR原桶強度單一麥芽威士忌(雪莉桶55.7)(扶輪社-窗系列二)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23P4H6-14',
        name: '0.5公升OMAR原桶強度單一麥芽威士忌(雪莉桶55.7)(扶輪社-酒之夢鄉)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23P4H8-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(PX雪莉桶52.5)(猴)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23P4H9-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(PX雪莉桶52.9)(雙虎圖)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23P4HT-14',
        name: '0.7公升原桶強度單一麥芽威士忌(酒展限定紀念梅子桶54.9)(大爵文創公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4HU-14',
        name: '0.7公升原桶強度單一麥芽威士忌(酒展限定紀念波本桶55.4)(大爵文創公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4J8-14',
        name: '0.7公升原桶強度麥芽威士忌(波本桶58.2)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4K5-14',
        name: '0.7公升原桶強度麥芽威士忌(雪莉桶57.8)(黑白道)(全球商行公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4K6-14',
        name: '0.7公升原桶強度麥芽威士忌(波本桶57.0)(臺灣稀有動物)(馬可波羅公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4K8-14',
        name: '0.7公升原桶強度麥芽威士忌(新橡木桶57.4%)(臺灣稀有動物)(礫石公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4K9-14',
        name: '0.7公升原桶強度麥芽威士忌(新橡木桶57.4%)《福爾摩沙古地圖》(麥村公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KA-14',
        name: '0.7公升原桶強度麥芽威士忌(波本桶57.6)《福爾摩沙古地圖》(麥村公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KB-14',
        name: '0.7公升原桶強度麥芽威士忌(新橡木桶56.1%)(梵輔天)(宇紳公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KC-14',
        name: '0.7公升原桶強度麥芽威士忌(波本桶57.8)(阿私陀)(宇紳公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KE-14',
        name: '0.7公升原桶強度麥芽威士忌(雪莉桶58.1)(濁水龍鰻)(大爵文創公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KF-14',
        name: '0.7公升原桶強度麥芽威士忌(雪莉桶57.8)(報恩白鹿)(大爵文創公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KG-14',
        name: '0.7公升原桶強度麥芽威士忌(新橡木桶56.8%)(濁水金鴨)(大爵文創公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KH-14',
        name: '0.7公升原桶強度麥芽威士忌(波本桶56.8)(護廠靈犬)(大爵文創公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KJ-14',
        name: '0.7公升原桶強度麥芽威士忌(波本桶57.9)(嘉德利亞蘭)(Ng訂製)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KK-14',
        name: '0.7公升原桶強度麥芽威士忌(新橡木桶55.9%)(台灣細葉七里香)(Ng訂製)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KL-14',
        name: '0.7公升原桶強度麥芽威士忌(新橡木桶57.5%)(車)(亞洲味蕾公司)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KS-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(雪莉桶57.5)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KT-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(波本桶55.7)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KU-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(新橡木桶58.3)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4KX-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(葡萄酒桶)(52%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4LG-14',
        name: '0.7公升*2原桶強度麥芽威士忌(奪魁稱雄)(泥煤波本56.0+泥煤波本58.2',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '23P4M0-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(PX雪莉桶52.2)(鹿)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23P4M1-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(PX雪莉桶52.9)(松鶴長年)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23P4M2-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌(荔枝酒桶)(56%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4M8-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌圓山總統行館小龍年典藏鎏金波本55.1%',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4M9-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌圓山總統行館小龍年典藏白金柳丁56.9%',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4N6-14',
        name: '0.7公升OMAR原桶強度單一麥芽威士忌圓山總統行館小龍年典藏鎏金波本56.3%',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23P4X6-39',
        name: '0.2公升*2原桶強度麥芽威士忌(波本桶55及雪莉桶58)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23P4Z6-14',
        name: '0.2公升*2原桶強度麥芽威士忌(波本桶56及雪莉桶58)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PB29-14',
        name: '1公升玉山12年金頂老窖禮盒(招財進寶)(財神爺)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23PB39-14',
        name: '1公升玉山12年金頂老窖禮盒(金雞聚寶)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23PD06-14',
        name: '0.2公升OMAR單一麥芽威士忌(雪莉果乾)(46%)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23PD07-14',
        name: '0.7公升OMAR單一麥芽威士忌(雪莉果乾)(46%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PD07-34',
        name: '0.7公升OMAR單一麥芽威士忌(雪莉果乾)(46%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PD0H-14',
        name: '0.7公升OMAR單一麥芽威士忌圓山70國宴紀念酒(46%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PD13-14',
        name: '0.7公升+0.05公升OMAR單一麥芽威士忌禮盒(波本花香)(幾何線條版)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PD16-14',
        name: '0.2公升OMAR單一麥芽威士忌(波本花香)(46%)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23PD17-14',
        name: '0.7公升OMAR單一麥芽威士忌(波本花香)(46%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PD17-34',
        name: '0.7公升OMAR單一麥芽威士忌(波本花香)(46%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PD30-14',
        name: '0.7公升OMAR單一麥芽威士忌ENCOUNTER 2023圓山國宴酒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PD38-14',
        name: '0.7公升OMAR單一麥芽威士忌(煙燻焦香)(46%)(八歌浪限定款)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PD47-14',
        name: '0.7公升OMAR單一麥芽威士忌(雪莉果乾)(46%)(總統府訂製酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PD51-14',
        name: '0.7公升+0.05公升OMAR單一麥芽威士忌禮盒(煙燻焦香)(龍年節慶版)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PD53-14',
        name: '0.7公升OMAR三桶單一麥芽威士忌(台灣特有種紀念版)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PD54-14',
        name: '0.7公升OMAR單一麥芽威士忌豐收系列No.5(46%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PD57-14',
        name: '0.7公升玉山單一麥芽威士忌(波本花香)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PD63-14',
        name: '0.7公升OMAR單一麥芽威士忌特別版(46%)(第16任總統就職紀念酒)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PD67-14',
        name: '0.7公升玉山單一麥芽威士忌(雪莉果乾)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PD82-14',
        name: '0.7公升OMAR單一麥芽威士忌(雪莉果乾)(113年國慶紀念酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PD83-14',
        name: '0.7公升OMAR單一麥芽威士忌豐收系列No.6(46%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PD9A-14',
        name: '0.7公升+0.2公升OMAR單一麥芽威士忌禮盒(雪莉果乾)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PDE7-14',
        name: '0.7公升OMAR單一麥芽威士忌(波本花香)(46%)(2019外交部訂製)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PDH7-14',
        name: '0.7公升OMAR單一麥芽威士忌特別版(46%)(第15任總統就職紀念酒)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PDL7-14',
        name: '0.7公升OMAR單一麥芽威士忌(南投縣酒)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PDS7-14',
        name: '0.7公升OMAR單一麥芽威士忌O Whisky圓山世界威士忌烈酒展紀念酒O版',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PDT7-14',
        name: '0.7公升OMAR單一麥芽威士忌圓山祕境花園會員聯誼會專用酒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PDU7-14',
        name: '0.7公升OMAR單一麥芽威士忌(煙燻焦香)(46%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PDY7-14',
        name: '0.7公升OMAR單一麥芽威士忌(雪莉果乾)2021圓山大飯店彩虹紀念酒-HUE',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PF00-14',
        name: '0.6公升玉山大曲酒(59.5%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PF01-14',
        name: '0.3公升玉山大曲',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23PF08-14',
        name: '0.08公升玉山大曲酒(59.5%)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PG01-14',
        name: '0.5公升*2玉山16年陳高禮盒(百年酒藏)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PG03-14',
        name: '0.9公升玉山台灣紅高粱16年陳高禮盒(如意蛇-彩繪版)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23PG04-14',
        name: '0.9公升玉山台灣紅高粱16年陳高禮盒(如意蛇-白金版)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23PJ10-14',
        name: '0.75公升玉山窖藏八年大麴原酒(武關公)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PJ11-14',
        name: '0.75公升玉山窖藏八年大麴原酒(封官端坐相)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23PK00-14',
        name: '0.7公升玉山台灣高粱酒九年陳高(紫氣東來)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PL01-14',
        name: '0.3公升玉山麥燒酎',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '23PN02-14',
        name: '0.75公升玉山台灣特級紅高粱酒八年陳高禮盒(一炮而紅)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PN19-14',
        name: '1.0公升玉山台灣特級紅高粱酒8年陳高禮盒(春燕報囍)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PS00-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶57.0)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS14-14',
        name: '0.7公升圓山總統行館牛年典藏鎏金泥煤單桶原酒(新橡木桶57.9)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PS15-14',
        name: '0.7公升圓山總統行館牛年典藏白金泥煤單桶原酒(新橡木桶57.2)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PS19-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(新橡木桶57.8)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS28-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(新橡木桶57.0五福臨門虎年紀念)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PS36-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶58.5)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23PS39-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶56.3)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS40-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶57.3)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS41-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶57.5)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS42-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶57.8)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS44-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶58.0)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS45-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶56.8)(貓老大)(佳賀)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS46-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本57.7)(大尖龍吞日-大爵)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS48-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶58.1)(威士忌小天地)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS49-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本56.7)(象棋版-包)(國泰',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS50-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶57.1)(龍過好年)(誠邦',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS51-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶56.6)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PS52-14',
        name: '0.7公升OMAR原桶強度單一泥煤麥芽威士忌(波本桶58.3)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PSA7-14',
        name: '0.7公升OMAR泥煤單一桶單一麥芽威士忌(56.0%)(豪邁選桶)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PSK7-14',
        name: '0.7公升OMAR原桶強度泥煤麥芽威士忌(波本桶55.7)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PSL7-14',
        name: '0.7公升OMAR原桶強度泥煤麥芽威士忌(波本桶56.3)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PSM7-14',
        name: '0.7公升OMAR原桶強度泥煤麥芽威士忌(波本桶56.5)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PSP7-14',
        name: '0.7公升OMAR原桶強度泥煤麥芽威士忌(波本桶55.2)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PSY7-14',
        name: '0.7公升OMAR原桶強度泥煤麥芽威士忌(波本桶58.3)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '23PU1A-14',
        name: '27公升玉山台灣珍藏紅高粱',
        unit: 'JA',
        quantity: '0  ',
    },
    {
        id: '23PX10-14',
        name: '0.6公升台酒玉山大曲八年甕藏(玻璃瓶)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23Q030-14',
        name: '0.6公升玉山高粱酒八年陳高(深海藍)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23Q400-14',
        name: '0.6公升玉山台灣八年陳高禮盒(雪花釉)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '23Q401-14',
        name: '1公升山之威密藏陳高(許文融美術館落成紀念酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23Q409-39',
        name: '1.0公升玉山台灣八年陳高禮盒(金頂榮耀)',
        unit: 'BOX',
        quantity: '4  ',
    },
    {
        id: '23Q601-14',
        name: '0.3公升台酒玉山陳高12年甕藏(紅麒麟)(品評用酒)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '23QD27-14',
        name: '0.7公升玉尊峰頂台灣威士忌',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '24001003-14',
        name: '0.7公升極CRAFT原桶強度台灣紅甘蔗單一蘭姆酒(57.2%)',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '2401A0-14',
        name: '0.6公升玉山福祿白蘭地',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '240302-14',
        name: '0.75公升玉山蘭姆酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '240604-14',
        name: '0.4公升閃耀之星伏特加',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '2406A2-14',
        name: '0.75公升玉山伏特加',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '2407A2-14',
        name: '0.75公升玉山琴酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '241607-14',
        name: '0.7公升玉山白蘭地X.O.禮盒(贈白蘭地杯1只)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '241717-14',
        name: '0.7公升玉山CRAFTSMAN荔枝白蘭地',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '242200-14',
        name: '0.6公升玉山白蘭地',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '242202-14',
        name: '20公升白蘭地料理酒(40%)',
        unit: 'L',
        quantity: '0  ',
    },
    {
        id: '242401-14',
        name: '0.7公升玉山CRAFTSMAN凍頂白蘭地',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '242500-14',
        name: '0.7公升玉山CRAFTSMAN白蘭地X.O.',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '242801-14',
        name: '0.7公升極CRAFT-蒔香',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '242802-14',
        name: '0.7公升極CRAFT-橙煦',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '242807-14',
        name: '0.7公升玉山極Craft-琴酒',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '25007001-14',
        name: '0.3公升*2玉山青梅竹馬',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '250402-14',
        name: '0.7公升雙鹿五加皮酒六十週年慶懷舊紀念酒禮盒',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '2512A5-34',
        name: '0.5公升外銷玉山竹葉青(瓷瓶)(45度)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '2519A7-14',
        name: '0.7公升玉山永康酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '2519B9-14',
        name: '0.7公升*2玉山永康酒禮盒(贈異麥芽寡醣1瓶)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '252500-14',
        name: '0.6公升公賣局紅標米酒水',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '253609-14',
        name: '0.1公升*2玉鶴陳年竹葉青酒(鼠年)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '253634-14',
        name: '0.1公升玉鶴陳年竹葉青禮盒-兔',
        unit: 'BOX',
        quantity: '24  ',
    },
    {
        id: '254109-39',
        name: '1公升玉鶴陳年五加(醉一擺酒瓶裝)',
        unit: 'BT',
        quantity: '9  ',
    },
    {
        id: '254302-14',
        name: '0.75公升玉鶴烏雞酒禮盒',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '254802-14',
        name: '0.7公升黃金竹葉青禮盒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '255201-14',
        name: '0.3公升玉山特級參茸酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '255301-14',
        name: '0.3公升玉山特級鹿茸酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '255501-14',
        name: '0.3公升玉山龍鳳酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '255600-14',
        name: '0.6公升玉山雙鹿五加皮酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '255601-14',
        name: '0.3公升玉山五加皮酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '255701-14',
        name: '0.3公升玉山竹葉青酒',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '255705-14',
        name: '0.5公升玉山竹葉青酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '26080A-14',
        name: '0.375公升玉泉烏梅酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '26082A-14',
        name: '0.375公升*2玉泉烏梅酒禮盒',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '26172A-14',
        name: '0.375公升*2玉泉桂花釀禮盒',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '262200-14',
        name: '0.6公升台酒特級玫瑰紅酒',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '26242A-14',
        name: '0.375公升*2玉泉青梅酒禮盒',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '271005-14',
        name: '0.5公升九十五度優質酒精',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '280107-14',
        name: '20公升料理米酒',
        unit: 'L',
        quantity: '0  ',
    },
    {
        id: '280309-14',
        name: '20公升台酒料理紅露酒',
        unit: 'DR',
        quantity: '0  ',
    },
    {
        id: '280319-14',
        name: '20公升料理紅露酒',
        unit: 'L',
        quantity: '0  ',
    },
    {
        id: '280400-14',
        name: '0.6公升稻香40度料理米酒',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '280402-14',
        name: '6公升稻香40度料理米酒(訂製)',
        unit: 'DR',
        quantity: '2  ',
    },
    {
        id: '281100-14',
        name: '0.6公升稻香58度料理米酒',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '282900-14',
        name: '0.6公升紅標料理米酒',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '282904-14',
        name: '6.0公升公賣局紅標料理米酒',
        unit: 'DR',
        quantity: '2  ',
    },
    {
        id: '282907-14',
        name: '20公升19.5度紅標料理米酒(公升計算)',
        unit: 'L',
        quantity: '0  ',
    },
    {
        id: '282930-14',
        name: '0.6公升紅標料理米酒(紙箱裝)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '283207-14',
        name: '20公升20度花雕料理酒',
        unit: 'DR',
        quantity: '1  ',
    },
    {
        id: '283804-14',
        name: '6公升台酒料理紹興酒',
        unit: 'DR',
        quantity: '0  ',
    },
    {
        id: '284100-14',
        name: '0.6公升紅標純米料理米酒',
        unit: 'BT',
        quantity: '20  ',
    },
    {
        id: '284103-14',
        name: '6公升公賣局紅標純米料理米酒',
        unit: 'DR',
        quantity: '2  ',
    },
    {
        id: '299056-14',
        name: '0.5公升*2台灣好酒龍鳳合鳴禮盒(狀元紅+女兒紅)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '34010001-12',
        name: '台酒黃金鳳梨冰棒(埔里)',
        unit: 'BAG',
        quantity: '0  ',
    },
    {
        id: '340102-12',
        name: '自製米糕冰棒(宜蘭)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '340104-12',
        name: '自製百香果冰(宜蘭)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '340107-12',
        name: '自製紅豆牛奶冰(宜蘭)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '340146-12',
        name: '台酒紹興米糕冰棒(新)(埔里)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '340148-12',
        name: '台酒紹興芋頭冰棒(新)(埔里)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '340151-12',
        name: '台酒烏梅黑麥汁冰棒(埔里)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '34020001-12',
        name: '台酒御膳堂-酒香蒙古鍋牛肉麵(12包/箱)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '34020005-12',
        name: '台酒麵攤-紹興櫻花蝦乾麵(16包/箱)',
        unit: 'BAG',
        quantity: '16  ',
    },
    {
        id: '34020006-12',
        name: '台酒御膳堂-雙椒嫩排麵(12包/箱)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '34020007-12',
        name: '台酒麵攤-鮮蝦魚板雙饗湯麵(16包/箱)',
        unit: 'BAG',
        quantity: '16  ',
    },
    {
        id: '34020008-12',
        name: '台酒御膳堂-椒麻牛肉雙寶麵(12包/箱)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '34020009-12',
        name: '台酒御膳堂-啤酒雞肉麵(12包/箱)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '34020010-12',
        name: '台酒御膳堂-藥膳排骨麵(12包/箱)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '340215-12',
        name: '台酒紅糟醬',
        unit: 'CAN',
        quantity: '12  ',
    },
    {
        id: '34040000-12',
        name: '台酒棗之道禮盒(紅露黑棗及桂花黑棗各一瓶)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '340409-12',
        name: '台酒紅露黑棗禮盒(600g*2罐/盒)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '34060013-12',
        name: '台酒琴酒香腸(6條/包/盒)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '34060014-12',
        name: '台酒花雕雞雙享香腸',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '340611-12',
        name: '自製烤酒香紅麴高粱香腸',
        unit: 'BR',
        quantity: '270  ',
    },
    {
        id: '340612-12',
        name: '自製酒香紹興香腸(1斤)',
        unit: 'TG',
        quantity: '0  ',
    },
    {
        id: '34130007-12',
        name: '0.33公升*6罐裝金牌FREE啤酒風味飲料 烈日芒果冰茶',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '34130008-12',
        name: '0.33公升*6罐裝金牌FREE啤酒風味飲料 星月荔枝烏龍',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '34130012-12',
        name: '0.33公升罐裝金牌FREE啤酒風味飲料 朝沁百香多',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '34130013-12',
        name: '0.33公升罐裝TTL纖麥汁',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '34130014-12',
        name: '0.33公升*6罐裝TTL纖麥汁',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '34130017-12',
        name: '0.33公升*6罐裝金牌FREE啤酒風味飲料 朝沁百香多',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '341361-12',
        name: '0.33公升罐裝金牌FREE啤酒風味飲料',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '341361-30',
        name: '0.33公升罐裝金牌FREE啤酒風味飲料(外銷)',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '341362-12',
        name: '0.33公升*6罐裝金牌FREE啤酒風味飲料',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '341368-12',
        name: '0.33公升*6罐裝TTL紅麴黑麥汁',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '341369-12',
        name: '0.33公升*6罐裝TTL桂圓黑麥汁',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '341370-12',
        name: '0.33公升罐裝TTL桂圓黑麥汁',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '341371-12',
        name: '0.33公升*6罐裝TTL烏梅黑麥汁',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '341372-12',
        name: '0.33公升*6罐裝TTL原味黑麥汁',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '341372-30',
        name: '0.33公升*6罐裝TTL原味黑麥汁(109年外銷新版)',
        unit: 'SET',
        quantity: '4  ',
    },
    {
        id: '341373-12',
        name: '0.33公升罐裝TTL烏梅黑麥汁',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '341374-12',
        name: '0.33公升罐裝TTL原味黑麥汁',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '341375-12',
        name: '0.33公升罐裝TTL紅麴黑麥汁',
        unit: 'CAN',
        quantity: '24  ',
    },
    {
        id: '341403-12',
        name: '自製紹興酒蛋(雞蛋)',
        unit: 'BAG',
        quantity: '0  ',
    },
    {
        id: '342002-12',
        name: '0.6公升玉泉寡醣果醋(金桔檸檬)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '342003-12',
        name: '0.6公升玉泉寡醣果醋(紅葡萄籽)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '342016-12',
        name: '台酒陳釀烏醋(0.3)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '342020-12',
        name: '台酒純釀米醋(0.3)(料理用)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '342024-12',
        name: '台酒米醋(酸度4.5%)(5.0)',
        unit: 'BT',
        quantity: '0  ',
    },
    {
        id: '342041-12',
        name: '0.6公升玉泉寡醣果醋(梅子)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '342055-12',
        name: '台酒健美醋禮盒[新版]',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '342065-12',
        name: '5公升台酒純(醇)釀米醋(酸度6%)(鹽3%)(抽出物6%)',
        unit: 'DR',
        quantity: '2  ',
    },
    {
        id: '342066-12',
        name: '5公升台酒純(醇)釀米醋(酸度5%)(抽出物6%)',
        unit: 'DR',
        quantity: '2  ',
    },
    {
        id: '35010003-12',
        name: '埔里1917出張所紅莓佳人冰淇淋',
        unit: 'CP',
        quantity: '0  ',
    },
    {
        id: '35020061-12',
        name: '台酒-紅酒燉牛肉麵(12包/箱)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '35020062-12',
        name: '台酒-紅酒燉牛肉麵(12碗/箱)',
        unit: 'BW',
        quantity: '12  ',
    },
    {
        id: '35020063-12',
        name: '台酒-川辣水煮牛肉麵(12包/箱)',
        unit: 'BAG',
        quantity: '12 ',
    },
    {
        id: '35020064-12',
        name: '台酒-川辣水煮牛肉麵(12碗/箱)',
        unit: 'BW',
        quantity: '12  ',
    },
    {
        id: '350216-12',
        name: '台酒酒粕糙米粥',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '350245-12',
        name: '台酒紅標米酒麻油雞麵(單包)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '350248-12',
        name: '台酒花雕雞麵(單包)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '350258-12',
        name: '台酒花雕酸菜牛肉麵(單包)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '350271-12',
        name: '台酒鹽麴(300g)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '350289-12',
        name: '台酒紅標米酒麻油雞麵(紙碗)',
        unit: 'BW',
        quantity: '12  ',
    },
    {
        id: '350290-12',
        name: '台酒花雕雞麵(紙碗)',
        unit: 'BW',
        quantity: '12  ',
    },
    {
        id: '350291-12',
        name: '台酒花雕酸菜牛肉麵(紙碗)',
        unit: 'BW',
        quantity: '12  ',
    },
    {
        id: '3502A2-12',
        name: '台酒麵攤-三杯雞風味乾麵(30包/箱)',
        unit: 'BAG',
        quantity: '30  ',
    },
    {
        id: '3502A5-12',
        name: '台酒麵攤-三杯雞風味乾麵(12碗/箱)',
        unit: 'BW',
        quantity: '12  ',
    },
    {
        id: '3502A6-12',
        name: '台酒漫煮食光－紹興香蔥拌麵（6袋/箱）',
        unit: 'PAC',
        quantity: '6  ',
    },
    {
        id: '3502A7-12',
        name: '台酒漫煮食光－鹽麴芝麻拌麵（6袋/箱）',
        unit: 'PAC',
        quantity: '6  ',
    },
    {
        id: '3502A8-12',
        name: '台酒麵攤-酒燉排骨風味湯麵(30包/箱)',
        unit: 'BAG',
        quantity: '30  ',
    },
    {
        id: '3502A9-12',
        name: '台酒麵攤-酒燉排骨風味湯麵(12碗/箱)',
        unit: 'BW',
        quantity: '12  ',
    },
    {
        id: '3502AC-12',
        name: '台酒紹興雪菜雞肉袋麵(12包/箱)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '35070039-12',
        name: '台酒紹興麻辣牛肉鍋(單鍋)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '350781-12',
        name: '台酒嚴選TOMMI花雕雞米漢堡8入',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '350856-12',
        name: '台酒嚴選海味街酒香土魠魚炊粉',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '35100022-12',
        name: '台酒紅麴捲心酥禮盒(日式抹茶/清新檸檬)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '3510BH-12',
        name: '台酒紅麴蔓越莓沙琪瑪(箱)',
        unit: 'CTN',
        quantity: '1  ',
    },
    {
        id: '35160132-12',
        name: '台啤-台灣美景玻璃杯400cc',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '35160135-12',
        name: '113年金牌ONE啤酒罐型玻璃杯',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '35160148-12',
        name: '台啤-紓壓捏捏罐',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '351646-12',
        name: '清酒粕潤膚皂',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '351693-12',
        name: 'OMAR珍藏木桶木盒',
        unit: 'PC',
        quantity: '4  ',
    },
    {
        id: '352149-12',
        name: '台酒寒天果醋晶凍(3口味-箱)',
        unit: 'CTN',
        quantity: '1  ',
    },
    {
        id: '352153-12',
        name: '台酒果醋口袋晶凍',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '35800117-30',
        name: 'PP 編織覆膜袋(贈品)',
        unit: 'PC',
        quantity: '420  ',
    },
    {
        id: '35800122-30',
        name: '台啤不鏽鋼露營杯-含杯蓋(贈品)',
        unit: 'PC',
        quantity: '100  ',
    },
    {
        id: '35800127-30',
        name: '台啤143 玻璃杯(贈品)',
        unit: 'PC',
        quantity: '96  ',
    },
    {
        id: '35800128-30',
        name: '台啤吸水杯墊(贈品)',
        unit: 'PC',
        quantity: '1160  ',
    },
    {
        id: '361004-12',
        name: '埔里清酒粕(250g/瓶)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '36130004-12',
        name: 'VINATA保濕抗皺精華液(30g/瓶)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '36170002-12',
        name: '酒好皂禮盒(111年新版-常態)(自製)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '36330000-12',
        name: 'VINATA抗皺活膚霜',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '36370001-12',
        name: '易洗樂洗潔組合(洗潔精+補充包升級版)',
        unit: 'BOX',
        quantity: '12  ',
    },
    {
        id: '36370002-12',
        name: '易洗樂洗潔精超值大包裝5公升(升級版)',
        unit: 'BT',
        quantity: '3  ',
    },
    {
        id: '36370003-12',
        name: '易洗樂洗潔精補充包600ml(升級版)',
        unit: 'BAG',
        quantity: '12  ',
    },
    {
        id: '36370004-12',
        name: '易洗樂洗潔精720ml(升級版)',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '363740-12',
        name: '1.6公升易洗樂抗菌防蟎洗衣精補充包',
        unit: 'BAG',
        quantity: '6  ',
    },
    {
        id: '363741-12',
        name: '2公升易洗樂抗菌防蟎洗衣精',
        unit: 'BT',
        quantity: '6  ',
    },
    {
        id: '365230-12',
        name: 'HIMO台酒異麥芽寡醣(健康食品核准)(450g/瓶)',
        unit: 'BT',
        quantity: '0  ',
    },
    {
        id: '36530000-12',
        name: 'VINATA啤酒花沐浴露',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '36530001-12',
        name: 'VINATA啤酒花洗髮精',
        unit: 'BT',
        quantity: '12  ',
    },
    {
        id: '37100000-12',
        name: '吃得比你好腸胃保健(犬用)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37100001-12',
        name: '吃得比你好關節保健(犬用)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37110002-12',
        name: '保暢益生菌',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37110005-12',
        name: 'S11益生菌(新規格)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37110007-12',
        name: '深海魚油軟膠囊(新規格)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '37130000-12',
        name: '激透光米植醇特潤膠囊(15顆)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37130028-12',
        name: '酒粕精粹逆齡活膚青春露金裝版(自)',
        unit: 'BT',
        quantity: '0  ',
    },
    {
        id: '37130029-12',
        name: 'VINATA激透光米植醇特潤膠囊(3顆)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37130030-12',
        name: 'VINATA保濕抗皺精華液(2g)',
        unit: 'BAG',
        quantity: '0  ',
    },
    {
        id: '37170002-12',
        name: '酒好皂(松炭)(111年新版)',
        unit: 'MAA',
        quantity: '0  ',
    },
    {
        id: '37170003-12',
        name: '酒好皂(清酒粕)(111年新版)',
        unit: 'MAA',
        quantity: '0  ',
    },
    {
        id: '37170004-12',
        name: '酒好皂(紅酒泥)(111年新版)',
        unit: 'MAA',
        quantity: '0  ',
    },
    {
        id: '37170005-12',
        name: 'VINATA啤酒花舒活香氛皂-小蒼蘭(112年新版)',
        unit: 'MAA',
        quantity: '0  ',
    },
    {
        id: '37170006-12',
        name: 'VINATA啤酒花舒活香氛皂-蓮香(112年新版)',
        unit: 'MAA',
        quantity: '0  ',
    },
    {
        id: '37170007-12',
        name: 'VINATA啤酒花舒活香氛皂-薰衣草(112年新版)',
        unit: 'MAA',
        quantity: '0  ',
    },
    {
        id: '37180001-12',
        name: '甘益守胜肽飲',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37180002-12',
        name: '甘益守胜肽飲禮盒',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37370005-12',
        name: 'VINATA啤酒花洗沐禮盒(新版)',
        unit: 'BOX',
        quantity: '6  ',
    },
    {
        id: '375005-12',
        name: 'VINATA專屬保養提袋(中)(180*215*105)',
        unit: 'ME',
        quantity: '0  ',
    },
    {
        id: '37510002-12',
        name: '保蜜益生菌',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37510003-12',
        name: '風淨益生菌',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '375132-12',
        name: '安可健納豆紅麴膠囊',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '375156-12',
        name: '安可健紅麴膠囊(健康食品核准)(60粒/瓶)',
        unit: 'BT',
        quantity: '0  ',
    },
    {
        id: '375165-12',
        name: '葉黃素軟膠囊(60顆/瓶)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '37530000-12',
        name: 'VINATA密集美白精華液(新)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37530001-12',
        name: 'VINATA密集美白乳液(新)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37530002-12',
        name: 'VINATA密集美白乳液體驗包',
        unit: 'BAG',
        quantity: '0  ',
    },
    {
        id: '37530003-12',
        name: 'VINATA密集美白精華液體驗包',
        unit: 'BAG',
        quantity: '0  ',
    },
    {
        id: '37530006-12',
        name: 'VINATA緊緻活膚膠囊(3顆)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '37530007-12',
        name: '激透光米植醇特潤膠囊(40顆)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '375358-12',
        name: 'VINATA緊緻活膚膠囊',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '375367-12',
        name: 'VINATA洗卸潔顏露',
        unit: 'BT',
        quantity: '0  ',
    },
    {
        id: '375380-12',
        name: '酒粕精粹逆齡活膚青春露(120ml/瓶)(阜助)',
        unit: 'BT',
        quantity: '0  ',
    },
    {
        id: '3753AD-12',
        name: 'VINATA酒粕維他命亮白面膜(8片/盒)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '3753AE-12',
        name: 'VINATA酒粕水嫩保濕面膜(8片/盒)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '3753BM-12',
        name: 'VINATA紅酒精華多重修護面膜(8片/盒)',
        unit: 'BOX',
        quantity: '0  ',
    },
    {
        id: '3753BX-12',
        name: 'VINATA酵母賦活精華輕潤身體乳(500ml)',
        unit: 'BT',
        quantity: '0  ',
    },
    {
        id: '3753C6-12',
        name: 'VINATA酵母賦活精華輕潤身體乳-輕巧瓶(50ml)',
        unit: 'BT',
        quantity: '36  ',
    },
    {
        id: '37800001-12',
        name: '50ml易洗樂洗潔精升級版(贈品)',
        unit: 'BT',
        quantity: '0  ',
    },
    {
        id: '385001-12',
        name: '易洗樂提袋',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '385102-12',
        name: '茄紅南瓜子油軟膠囊(60顆/瓶)',
        unit: 'BT',
        quantity: '24  ',
    },
    {
        id: '6-001100600100',
        name: '0.6L20支塑膠箱',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-001300100200',
        name: '塑膠棧板(成品用)120*100*16cm單面',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-001300100201',
        name: '塑膠棧板(成品)120*100*16-17cm',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-002301400100',
        name: '一般標準棧板132cm*108*14',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-002301401000',
        name: '其他舊式棧粄(未指定規格)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-002301401100',
        name: '雙面瓶裝棧板',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-002301401200',
        name: '雙面罐裝棧板',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-002301401201',
        name: '雙面紅板棧板(罐裝)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-002301401300',
        name: '單面裝載十字口型塑膠棧板',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-002301401400',
        name: '單面裝載十字口型塑膠棧板(罐裝)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-002301402000',
        name: '化妝品倉儲用塑膠棧板(1*1米)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-002301402100',
        name: '化妝品用倉儲塑膠棧板(1.2*1.2米)',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-070000100100',
        name: '30L K桶',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-070000100110',
        name: '10L K桶',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-070000100120',
        name: '20L K桶',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '6-070000100130',
        name: '40L C桶',
        unit: 'PC',
        quantity: '0  ',
    },
    {
        id: '8-4524-001-00174-0',
        name: '押酒器',
        unit: 'PC',
        quantity: '0 ',
    },
]);

const filteredData = computed(() => {
    return data.value.filter(
        (item) =>
            searchQuery.value === '' ||
            (item.id.startsWith(searchQuery.value) && item.id.includes(searchQuery.value)) ||
            item.name.includes(searchQuery.value)
    );
});
</script>
